cloud:
  aws:
    credentials:
      access-key: # IAM access-Key 입력
      secret-key: # IAM secret-Key 입력
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: jkproject
      project: /project/
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB