spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          timeout: 5000
        smtps:
          checkserveridentity: true
        debug: true

