--DROP TABLE if EXISTS member cascade;
--DROP TABLE if EXISTS PROJECT cascade;
--DROP TABLE if EXISTS TOKEN cascade;
--DROP TABLE if EXISTS VIDEO cascade;
--DROP TABLE if EXISTS TEMP_AUDIO cascade;
DROP TABLE if EXISTS IMAGE cascade;
DROP TABLE if EXISTS VOICE cascade;

CREATE TABLE IMAGE
(
    IMAGE_ID BIGINT NOT NULL AUTO_INCREMENT,
    CATEGORY VARCHAR(255),
    IMAGE_NAME VARCHAR(255),
    IMAGE_URL VARCHAR(255),
    PRIMARY KEY (IMAGE_ID)
);

CREATE TABLE VOICE
(
    VOICE_ID BIGINT NOT NULL AUTO_INCREMENT,
    LANGUAGES VARCHAR(255),
    SEX VARCHAR(255),
    VOICE_NAME VARCHAR(255),
    VOICE_URL VARCHAR(255),
    PRIMARY KEY (VOICE_ID)
);
